// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvgujfwbsiafpkivrvoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2Z3VqZndic2lhZnBraXZydm9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTI4NDAsImV4cCI6MjA1OTc4ODg0MH0.62_GSIW9iXv7kqOVy-AxsUWC8XOAT4P6DdDD4jAe45w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);